resource_types:
  - name: metadata
    type: docker-image
    source:
      repository: swce/metadata-resource

resources:
  - name: metadata
    type: metadata

jobs:
  - name: metadata
    plan:
      - get: metadata
      - task: print
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: busybox
          inputs:
            - name: metadata
          run:
            path: sh
            args:
              - -c
              - |
                find ./metadata -type f -exec sh -c 'echo "$(basename {}): $(cat {})"' \; | sort
