resource_types:
  - name: test-resource
    type: docker-image
    source:
      repository: ajapon88/concourse-test-resource

resources:
  - name: test-resource
    type: test-resource
    source:
      config1: config-value1
      config2: config-value2

jobs:
  - name: sample
    plan:
      - get: test-resource
        # trigger: true
        params:
          get_param1: get-param-value1
      - put: test-resource
        params:
          put_param1: put-param-value1
