resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: test_gem
  type: pull-request
  check_every: 1m
  source:
    repository: ajapon88/test_gem
    access_token: ((github-access-token))

jobs:
- name: spec
  public: true
  plan:
  - get: test_gem
    trigger: true
    version: every
  - put: test_gem
    params:
      path: test_gem
      status: pending
      context: spec
  - task: spec
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ruby
          tag: 2.7
      inputs:
      - name: test_gem
      caches:
      - path: test_gem/vendor/bundle
      run:
        path: sh
        args:
        - -xce
        - |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rake spec
        dir: test_gem
    on_failure:
      put: test_gem
      params:
        path: test_gem
        status: failure
        context: spec
  - put: test_gem
    params:
      path: test_gem
      status: success
      context: spec
