version: '3'

services:
  concourse-db:
    image: postgres:12.1
    volumes: ["./database:/database"]
    environment:
      POSTGRES_DB: ${CONCOURSE_POSTGRES_DATABASE}
      POSTGRES_USER: ${CONCOURSE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CONCOURSE_POSTGRES_PASSWORD}
      PGDATA: /database

  concourse-web:
    image: concourse/concourse:5.8.0
    command: web
    depends_on: [concourse-db]
    ports: ["8080:8080", "2222:2222"]
    volumes: ["./keys/web:/concourse-keys"]
    restart: unless-stopped
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: ${CONCOURSE_POSTGRES_USER}
      CONCOURSE_POSTGRES_PASSWORD: ${CONCOURSE_POSTGRES_PASSWORD}
      CONCOURSE_POSTGRES_DATABASE: ${CONCOURSE_POSTGRES_DATABASE}
      CONCOURSE_EXTERNAL_URL: ${CONCOURSE_EXTERNAL_URL}
      CONCOURSE_ADD_LOCAL_USER: ${CONCOURSE_ADD_LOCAL_USER}
      CONCOURSE_MAIN_TEAM_LOCAL_USER: ${CONCOURSE_MAIN_TEAM_LOCAL_USER}
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: ${CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER}

  concourse-worker:
    image: concourse/concourse:5.8.0
    command: worker
    privileged: true
    depends_on: [concourse-web]
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web:2222
      CONCOURSE_NAME: concourse-worker
