version: "3"

services:
  concourse-db:
    image: postgres:12.1
    volumes:
      - ./volumes/database:/database
    environment:
      POSTGRES_DB: ${CONCOURSE_POSTGRES_DATABASE}
      POSTGRES_USER: ${CONCOURSE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CONCOURSE_POSTGRES_PASSWORD}
      PGDATA: /database

  concourse-web:
    image: concourse/concourse:5.8.0
    command: web
    depends_on:
      - concourse-db
    ports:
      - 8080:8080
      - 2222:2222
    volumes:
      - ./keys/web:/concourse-keys
    restart: unless-stopped
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: ${CONCOURSE_POSTGRES_USER}
      CONCOURSE_POSTGRES_PASSWORD: ${CONCOURSE_POSTGRES_PASSWORD}
      CONCOURSE_POSTGRES_DATABASE: ${CONCOURSE_POSTGRES_DATABASE}
      CONCOURSE_EXTERNAL_URL: ${CONCOURSE_EXTERNAL_URL}
      CONCOURSE_ADD_LOCAL_USER: ${CONCOURSE_ADD_LOCAL_USER}
      CONCOURSE_MAIN_TEAM_LOCAL_USER: ${CONCOURSE_MAIN_TEAM_LOCAL_USER}
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: ${CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER}
      CONCOURSE_VAULT_URL: http://vault:8200
      CONCOURSE_VAULT_CLIENT_TOKEN: ${CONCOURSE_VAULT_CLIENT_TOKEN}
      CONCOURSE_VAULT_PATH_PREFIX: ${CONCOURSE_VAULT_PATH_PREFIX}
      CONCOURSE_VAULT_SHARED_PATH: ${CONCOURSE_VAULT_SHARED_PATH}
      CONCOURSE_VAULT_INSECURE_SKIP_VERIFY: "true"

  concourse-worker:
    image: concourse/concourse:5.8.0
    command: worker
    privileged: true
    depends_on:
      - concourse-web
    volumes:
      - ./keys/worker:/concourse-keys
    environment:
      CONCOURSE_TSA_HOST: concourse-web:2222
      CONCOURSE_NAME: concourse-worker

  vault:
    build: ./vault
    command: server -dev
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/scripts:/vault/scripts
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${CONCOURSE_VAULT_CLIENT_TOKEN}
      VAULT_ADDR: http://127.0.0.1:8200
      POST_COMMAND: /vault/scripts/init

  minio:
    image: minio/minio:RELEASE.2020-02-07T23-28-16Z
    command: server /data
    volumes:
      - ./volumes/minio/data:/data
    ports:
      - 9000:9000
    environment:
      MINIO_REGION: ${MINIO_REGION}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

  docker-registry:
    image: registry:2.7.1
    volumes:
      - ./volumes/registry:/var/lib/registry
    ports:
      - 5000:5000
