#!/bin/sh -eu

apk add --no-cache -f -q jq

cd $(dirname ${0})

echo "> vault login"
vault login "${VAULT_DEV_ROOT_TOKEN_ID}"

echo "> vault policy write concourse"
cat <<EOF | vault policy write concourse -
path "concourse/*" {
  policy = "read"
  capabilities =  ["read", "list"]
}
EOF

echo "> vault secrets enable"
vault secrets enable -version=1 -path=concourse kv

if [ -e ./secrets.json ]; then
  echo "> vault write from secrets.json"
  json=$(cat secrets.json)
  for key in $(echo $json | jq -r keys[]); do
    vault write "concourse/main/${key}" value="$(echo $json | jq -r ".[\"$key\"]")"
  done
fi
