#!/usr/bin/env bash

set -e -u

cd $(dirname $0)

CONCOURSE_IMAGE=concourse/concourse

if [ "$(expr substr $(uname -s) 1 5 2>/dev/null)" == 'MINGW' -o "$(expr substr $(uname -s) 1 7 2>/dev/null)" == 'MSYS_NT' ]; then
  export MSYS_NO_PATHCONV=1
  keys_path=$(pwd)
  mount_keys_path=/${keys_path}
else
  keys_path=$(pwd)
  mount_keys_path=${keys_path}
fi

generate-key() {
  local keytype=$1
  local output=$2
  local keyname=$3
  docker run --rm -v "${mount_keys_path}/${output}:/keys" "${CONCOURSE_IMAGE}" \
    generate-key -t "${keytype}" -f "/keys/${keyname}"
}

if [ ! -e "${keys_path}/web/session_signing_key" ]; then
  echo "generate session_signing_key"
  generate-key rsa web session_signing_key
fi

if [ ! -e "${keys_path}/web/tsa_host_key" ]; then
  echo "generate tsa_host_key"
  generate-key ssh web tsa_host_key
fi

if [ ! -e "${keys_path}/worker/worker_key" ]; then
  echo "generate worker_key"
  generate-key ssh worker worker_key
fi

rm -f "${keys_path}/web/authorized_worker_keys"
cat "${keys_path}/worker/worker_key.pub" >>"${keys_path}/web/authorized_worker_keys"
cp "${keys_path}/web/tsa_host_key.pub" "${keys_path}/worker"
